### ISSUE TITLE
Open ID 2.0 No longer supported by Google

### ISSUE THREAD

**Issue by danwalkeriv** [tmeers/Derby#6]
Attempting to login using Google as the Open ID provider gives the following error:
https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by tmeers** [comment]
Sadly you're correct. I need to visit this and update to the currently supported method. I hope to be reviewing this soon!

**Comment by tmeers** [comment]
Added support for Google OpenId Connect.
